### PR TITLE
Add CodeQL scanning

### PR DESCRIPTION
**Pull request by joshma**
This file was autogenerated by GH - was thinking we could add to repo just to see what happens.

### CODE REVIEW

**Review by colinking — APPROVED** [review]
Did this just count the lines of code? 🤔 That's all it looks like it did from the metrics in the GHA run.

**Comment by joshma** [comment]
It only runs on main lol, so we'll see what it does!

**Comment by joshma** [comment]
Wait nevermind, it doesn't? Taking another look.

**Comment by joshma** [comment]
screenshot_20210729_a8tZU8Do

^ looks like the metrics is just some outputs it can produce, but there's a lot of queries that don't have metrics

**Pull request merged**
