### PR TITLE
Downgrade go-git dependency

### PR DESCRIPTION
**Pull request by calufornia**
## Description

go-git introduced a transitive dependency on cgo, which Goreleaser does not currently support compiling with (at least our current setup). This is causing releases to fail: https://github.com/airplanedev/cli/actions/runs/3659296995/jobs/6185307857. Downgrade and anchor the dependency for now.

## Test plan
n/a

### CODE REVIEW

**Comment by leeweisberger** [comment]
Is there a github issue tracking this that you can subscribe to?

**Comment by calufornia** [comment]
> Is there a github issue tracking this that you can subscribe to?

Yep, they are fixing it here: https://github.com/go-git/go-git/pull/625

**Comment by calufornia** [comment]
I think the fix will come in soon so probably don't need the renovate ignore

**Review by leeweisberger — APPROVED** [review]
to unblock the release. Let's roll forward once their fix is in

**Comment by leeweisberger** [comment]
We're rolling back forward w/fix https://github.com/airplanedev/cli/pull/858

**Pull request merged**
