### PR TITLE
Run staticcheck

### PR DESCRIPTION
**Pull request by yields**
I ran staticcheck on the repo, it follows:
https://github.com/golang/go/wiki/CodeReviewComments

Let me know if anyone feels strongly about keeping the "this" receiver.

### CODE REVIEW

**Comment by joshma** [comment]
> Let me know if anyone feels strongly about keeping the "this" receiver.

😂  @colinking

**Comment by colinking** [comment]
Yeah, I prefer to use a standard receiver name. I generally disagree with https://github.com/golang/go/wiki/CodeReviewComments#receiver-names because:

1) **Refactoring**: If the receiver's name reflects the type's name, then it falls out of date as you change type's name.
2) **Interfaces**: Interfaces have multiple implementations, each with receivers. It's easy enough to copy a declaration and forget to change the the receiver name. When diffing two implementations with similar code, you end up with unnecessary deltas b/c of different receiver names.
3) **Functional Output**: A core part of this recommendation is this statement: *"In Go, the receiver of a method is just another parameter and therefore, should be named accordingly."* How often do you write functions that emit side effects through their parameters? The main exception to that is code similar to `json.Marshal` who returns its data through a pointer. On the other hand, side effects to a receiver are commonplace (f.e. `this.myProperty = "123"`). The fact that receivers are parameters under-the-hood is irrelevant considering the conventions are different.
4) **Readability**: While reading code, you have to remember the receiver name to know if a variable is the receiver or not. If the receiver is always `this`, then that's one less bit of information to remember while reading someone else's code.

Hehe, so yeah. Alas, it's the Go recommendation so what can I do :)

**Comment by joshma** [comment]
Meh, I think this has me leaning towards agreeing with the golang code guidelines.

> 1. **Refactoring**: If the receiver's name reflects the type's name, then it falls out of date as you change type's name.

Yeah, this is true. But it's the same as what happens to variables (`client := APIClient{}`).

> 2. **Interfaces**: Interfaces have multiple implementations, each with receivers. It's easy enough to copy a declaration and forget to change the the receiver name. When diffing two implementations with similar code, you end up with unnecessary deltas b/c of different receiver names.

I don't think the "we have the same code everywhere" argument is that great, don't think we should optimize for that.

> 3. **Functional Output**: A core part of this recommendation is this statement: _"In Go, the receiver of a method is just another parameter and therefore, should be named accordingly."_ How often do you write functions that emit side effects through their parameters? The main exception to that is code similar to `json.Marshal` who returns its data through a pointer. On the other hand, side effects to a receiver are commonplace (f.e. `this.myProperty = "123"`). The fact that receivers are parameters under-the-hood is irrelevant considering the conventions are different.

I think this is handled by pointer vs non-pointers. You actually can't have a side-effect for non-pointers! And if it's a pointer, either way (param or receiver), you can have side-effects.

> 4. **Readability**: While reading code, you have to remember the receiver name to know if a variable is the receiver or not. If the receiver is always `this`, then that's one less bit of information to remember while reading someone else's code.

I think this is actually part of the intention behind the guideline - you don't have to know the difference! It's just another variable.

**Comment by yields** [comment]
Kinda agree with Go's guidelines too since it's all over in there stdlib and the wider community.

**Comment by francescaleung** [comment]
Just adding my two cents, but I'm leaning towards Go guidelines as well. I've used `this` in the past because it was already in the codebase ("code like no one knows you've been there") but it always felt weird to me.

**Comment by joshma** [comment]
Let's wait for @colinking to get back, bikeshed over this, and resolve :)

**Comment by colinking** [comment]
Heh thanks, but no need to have waited on me for this. Let's stick to Go conventions! Linting rules ftw

**Comment by colinking** [comment]
@yields can we add this as a lint step in GHA?

**Comment by yields** [comment]
> However, we have some `this` receivers in `airport` so now I'm curious why they didn't get flagged there... 🤔

Perhaps golangci-lint disables that check by default, I know that staticcheck allows users to disable any checks. but by default running the recent `staticcheck(1)` on this repo this is what I get:

```text
  λ cli (main) staticcheck ./...
pkg/taskdir/directory.go:69:7: receiver name should be a reflection of its identity; don't use generic names such as "this" or "self" (ST1006)
```

**Comment by yields** [comment]
@colinking mind approving? :)

**Review by colinking — APPROVED** [review]

**Pull request merged**
